name: Artifact upload download testing

on: [workflow_dispatch]


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create artifact
      run: |
       mkdir -p abc
       echo hello > world.txt

    - name: Display structure of created files
      run: ls -R

    - name: Upload all artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
#         path: world.txt # Let's see what happens, this should upload everything, whatever that means
        

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: Display structure of downloaded files
      run: ls -R
