name: Artifact upload download testing

on: [push, workflow_dispatch]


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create artifact
      run: |
       mkdir -p abc
       echo hello > abc/world.txt

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: Display structure of downloaded files
      run: ls -R

    - name: Upload all artifacts
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: abc/world.txt
        

    - name: Download all artifacts
      uses: actions/download-artifact@v3
      with:
        name: my-artifact

    - name: Display structure of downloaded files
      run: ls -R
